@startuml

!if ($bootstrapIncluded == false)
  !$bootstrapIncluded = true

  !if %variable_exists("$title")
    title $title
  !endif

  !include includes/skinparams.iuml

  !include actors.puml

    == Flows ==
!endif

@enduml
